name: task_05
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^10.1.0
  
  cupertino_icons: ^1.0.6
  device_preview: ^1.0.0+3
  firebase_core: ^3.6.0
  firebase_auth: any
  cloud_firestore: ^5.4.4
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^7.1.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/manage_image.png
    - lib/assets/daily_image.png
    - lib/assets/organize_image.png
    - lib/assets/logo.png
    - lib/assets/index.png
    - lib/assets/add.png
    - lib/assets/bread.png
    - lib/assets/briefcase.png
    - lib/assets/design.png
    - lib/assets/heartbeat.png
    - lib/assets/home.png
    - lib/assets/megaphone.png
    - lib/assets/mortarboard.png
    - lib/assets/music.png
    - lib/assets/sport.jpg
    - lib/assets/video-camera.png

uses-material-design: true